### ISSUE TITLE
Output is unwrapped by closure

### ISSUE THREAD

**Issue by machty** [ghempton/ember-script-rails#1]
Need some way of enabling/configuring the equivalent `--bare` option for EmberScript so that each file gets wrapped in a closure, like vanilla CoffeeScript

(also, fwiw, I recognize that this is all super new so if you want me to lay off the github issues, just lemme know)

edit: I'm also not sure where the divide is between emberscript rails and normal emberscript, so maybe this belongs in the other repo

**Comment by ghempton** [comment]
@machty this is already supported by the underlying compiler, just needs to be exposed in [ember-script-ruby](https://github.com/ghempton/ember-script-ruby) (which is currently just a lightweight wrapper on the command)

**Comment by machty** [comment]
ok, may I have the honor of adding that in?

On Mon, Dec 24, 2012 at 1:19 AM, Gordon L. Hempton <notifications@github.com

> wrote:
> 
> @machty https://github.com/machty this is already supported by the
> underlying compiler, just needs to be exposed in ember-script-rubyhttps://github.com/ghempton/ember-script-ruby(which is currently just a lightweight wrapper on the command)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ghempton/ember-script-rails/issues/1#issuecomment-11655042.

## 

# 

Alex Matchneer
Co-Founder and Lead Dev
Useful Robot LLC
http://usefulrobot.io
(614) 395-8832

**Comment by ghempton** [comment]
Absolutely, `ember-script` takes a `--bare` option. Would also be good to have this exposed somehow `ember-script-rails`. Maybe follow the same conventions as the coffee-rails gem?

**Comment by machty** [comment]
coffee-rails doesn't expose the `bare` option in any meaningful way rather
than requiring you to explicitly set the option provided in
coffee-script-ruby. I spose we can leave this issue open, but the PR will
eventually be for ember-script-ruby

On Mon, Dec 24, 2012 at 1:29 AM, Gordon L. Hempton <notifications@github.com

**Comment by machty** [comment]
False alarm, closure-wrapping is working just fine. Fun fact: CoffeeScript
is smart enough to not wrap code where no local var assignments are being
made. I'm still going to be submitting a PR for enabling/disabling
wrapping, just because it's nearly done anyway, but feel free to close this.
